### ISSUE TITLE
Make some georeference analyses less demanding

### ISSUE THREAD

**Issue by javierarce** [CartoDB/camshaft#128]
Certain georeference analyses, like `georeference-admin-region` and `georeference-city` require to send all the params. Would it be possible to make them optional, like we do in `georeference-street-address`?

cc: @saleiva

**Comment by dgaubert** [comment]
If params that we send to our [geocoder-service](https://carto.com/docs/carto-engine/dataservices-api/geocoding-functions/#level-1-administrative-regions-geocoder) are optional then we can make those params optional in analysis too.

**Comment by dgaubert** [comment]
I've checked with data-services and those params can be optional.

**Comment by javierarce** [comment]
That's great! Then all we need to do is update the camshaft-reference to make them optional, right?

**Comment by dgaubert** [comment]
that's it! I'll take care of it.

**Comment by saleiva** [comment]
I cannot find the reference for this ticket in the cartodb repo.

**Comment by javierarce** [comment]
There's no ticket for that in the cartodb repo. Once the reference is updated, the UI won't require those fields.

**Comment by saleiva** [comment]
Cooleo, thanks!

**Comment by iriberri** [comment]
Hey there! I've noticed a couple things [here](https://github.com/CartoDB/camshaft/blob/master/lib/node/nodes/georeference-admin-region.js) (georeference-admin-region).

* The city parameter is part of the code (we don't geocode cities as regions right now besides the namedplaces geocoding), which I assume is a typo when copy-pasting analysis :)
* Only the admin1 function is being used (unless I missed something). For countries, the admin0 function should be used. I found out about this while debugging the country decoder which seems to be trying something like `geocode_admin1_polygon('Spain, Spain').

**Comment by dgaubert** [comment]
@iriberri thanks for your comments. I'm fixing them.

**Comment by dgaubert** [comment]
> Only the admin1 function is being used (unless I missed something). For countries, the admin0 function should be used. I found out about this while debugging the country decoder which seems to be trying something like geocode_admin1_polygon('Spain, Spain').

AFAIK we don't have analysis for country geocoding.

**Comment by saleiva** [comment]
It's there. Is the admin region, when the country field is empty

On Jul 13 2016, at 12:57 pm, Daniel &lt;notifications@github.com&gt; wrote:  

> > Only the admin1 function is being used (unless I missed something). For
countries, the admin0 function should be used. I found out about this while
debugging the country decoder which seems to be trying something like
geocode_admin1_polygon('Spain, Spain').

>

> AFAIK we don't have analysis for country geocoding.

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/CartoDB/camshaft/issues/128#issuecomment-232323097),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAIENbjKtkJ1Nh0ZivN957IaC0qOk5rsks5qVMSfgaJpZM4JHRss).![](https://github.com/notifications/beacon/AAIENZuKy08lLvsxgl9nVe5NeqzBc8Itks5qVMSfgaJpZM4JHRss.gif)

**Comment by dgaubert** [comment]
Opps! I didn't know that. Fixing it.

**Comment by dgaubert** [comment]
FYI: from #138, I've added a new analysis: `georeference-country`. This analysis receives a mandatory param `country_colum` as column value.

**Comment by dgaubert** [comment]
Closed by #141
