### ISSUE TITLE
Georeference analyses should allow to use a custom text input instead of a column name

### ISSUE THREAD

**Issue by javierarce** [CartoDB/camshaft#137]
Working on this issue https://github.com/CartoDB/cartodb/issues/8759 I've realized that certain analysis (like `georeference-city`) always expect column names as input params and retrieve an error if that's not the case:

```javascript
{
    "errors": [
        "column \"Island\" does not exist"
    ],
    "errors_with_context": [
        {
            "type": "analysis",
            "message": "column \"Island\" does not exist",
            "analysis": {
                "id": "b1",
                "type": "georeference-city"
            }
        }
    ]
}
```

To maintain the same functionality of the old editor, we should allow sending arbitrary texts and not only columns.

Also, note that currently, if the user sends a couple of words separated by an space, the API returns an error (in this example I sent 'Trinidad and Tobago' as the country):

```javascript
{
    "errors": [
        "column \"trinidad\" does not exist"
    ],
    "errors_with_context": [
        {
            "type": "analysis",
            "message": "column \"trinidad\" does not exist",
            "analysis": {
                "id": "b1",
                "type": "georeference-city"
            }
        }
    ]
}
```

**Comment by dgaubert** [comment]
That's why we are building the analysis query in a bad way. Params should be passed as string ones.

On it.
