### ISSUE TITLE
Tables not present in cdb_tablemetadata will retrigger analyses

### ISSUE THREAD

**Issue by rochoa** [CartoDB/camshaft#143]
Any table in a source node that is not present in `cdb_tablemetadata` will get a `Date.now()` timestamp as last modification date, triggering the analyses again as data might have changed.

The options we have are:
 - Freeze last modification date for queries with no tables in `cdb_tablemedatada`, or not tables at all, with a date in the past.
 - Raise an error asking the user to cartodbfy the table, and register it in `cdb_tablemetadata`. This option doesn't solve the issue with queries not having tables, for instance, function calls like `random`.

cc @saleiva @javisantana

**Comment by xavijam** [comment]
Happened with a table from @miguelarias, more info here: https://github.com/CartoDB/cartodb/issues/9141.
