### ISSUE TITLE
Moran's I failing on this dataset

### ISSUE THREAD

**Issue by saleiva** [CartoDB/camshaft#161]
This is the error that I get when trying to do an analysis using the price or the availability_365 columns on 
[listings.csv.zip](https://github.com/CartoDB/camshaft/files/395549/listings.csv.zip)

{"node_id":"5d19641e6ab70fc982d0ea2c2afe341b8cccf693","status":"failed","updated_at":"2016-08-02T08:09:57.392Z","error_message":"plpy.Error: Error: areas of interest query failed, check input parameters"}

It works correctly in https://team.carto.com/u/saleiva/dataset/airbnb_listings_sample_nyc_jan1_3

**Comment by ohasselblad** [comment]
This is taken care of with crankshaft v1.5.0: https://github.com/CartoDB/crankshaft/commit/f8739b6a686bc8fabe45c82f4fca727b465d65f3
