### ISSUE TITLE
line-source-to-target to closest

### ISSUE THREAD

**Issue by rochoa** [CartoDB/camshaft#185]
Using [Untitled Map 12 (on 2016-08-29 at 13.23.43).carto.zip](https://github.com/CartoDB/camshaft/files/442474/Untitled.Map.12.on.2016-08-29.at.13.23.43.carto.zip) you will find that "to closest" option only shows the closest metro relative to all stations.

I would expect to have the closest metro station for each centroid, and not just the closest, in general, one.

cc @javierarce @saleiva

**Comment by dgaubert** [comment]
Taking a look, the final query is:

```
SELECT * FROM (SELECT *, rank() OVER (PARTITION BY null ORDER BY length ASC) AS rank FROM ( ... ) _cdb_filter_grouped_rank) _camshaft_range_filter WHERE rank <= 1
```
where the column used in `PARTITION BY` is null 

Also, the params of the analysis:
```
{
    type: "line-source-to-target",
    source: "7b03095b9b0a1b0edb3da3e5998832ccfa989557",
    source_column: null,
    target: "bbbcebbbc5c736559aada6fbfc498d94b8d2ee37",
    target_column: "cartodb_id",
    closest: true
}
```
In this case, `source_column` is `null` and using `to closest` option applies the filter `grouped-rank` in a bad way. 

I'd would expect to throw an error when the option `to closest` is true and `source_column` is not defined.

BTW, setting `source_column` to `cartodb_id` the analysis would work as expected.

**Comment by dgaubert** [comment]
I've tried to set `source_column` to `cartodb_id` using the Builder:
![image](https://cloud.githubusercontent.com/assets/1936888/18177177/50514e8e-7079-11e6-8a77-f7c8ab4a5f7e.png)

But I couldn't. The field `target col` does not show `cartodb_id`.

**Comment by saleiva** [comment]
Not even if you type cartodb_id there?

**Comment by dgaubert** [comment]
Nope

**Comment by saleiva** [comment]
Be sure you check with @javierarce tomorrow then... let's try to get this fixed so we can look to the future 💯

**Comment by javierarce** [comment]
I'm adding a ticket to fix this.

**Comment by dgaubert** [comment]
BTW, I think the query is not doing what is expected, at least for this use case. On it

**Comment by dgaubert** [comment]
It's much better, isn't it?

![image](https://cloud.githubusercontent.com/assets/1936888/18244998/1a31d2be-7363-11e6-96dd-2b2bf5be4b9b.png)
