### ISSUE TITLE
[Analysis] Populate the_geom_webmercator (EPSG:3857) in cache tables

### ISSUE THREAD

**Issue by rochoa** [CartoDB/camshaft#200]
In order to avoid `st_transform(the_geom, 3857)` when rendering.

The best alternative is to use https://github.com/CartoDB/cartodb-postgresql/blob/091aea088e1d37290dbac9d602256d0ececd50bb/scripts-available/CDB_TransformToWebmercator.sql.

Fixes #134.

**Comment by rafatower** [comment]
I checked a bunch of analyses and that column seems to be populated. Is this to be done yet or can this issue be closed?

**Comment by rochoa** [comment]
It's not. If the analysis in question augments the table it will reuse the existing `the_geom_webmercator`, however, when the geometry is transformed, `the_geom_webmercator` is not created/updated (check buffer analysis, for instance). What happens behind the scenes is that if `the_geom_webmercator` column is not found, we `ST_Transform(the_geom, 3857) as the_geom_webmercator` on the fly.

**Comment by ethervoid** [comment]
Maybe we could make a quick fix changing [here](https://github.com/CartoDB/Windshaft-cartodb/blob/master/lib/cartodb/models/mapconfig/adapter/analysis-mapconfig-adapter.js#L184) and [here](https://github.com/CartoDB/Windshaft-cartodb/blob/master/lib/cartodb/models/mapconfig/adapter/analysis-mapconfig-adapter.js#L197) and have more time to make this change properly.

What do you think @rochoa ?

**Comment by ethervoid** [comment]
I've put it on hold until we can talk about it because I read the conversation between @rochoa and @javisantana [here](https://github.com/CartoDB/camshaft/issues/201) and I want to know more about this issue before spending time on it.

Maybe the fix I propose in my last comment could be a quick solution for the current problems the users are having.
