### ISSUE TITLE
Compute analysis requirements before executing them

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/camshaft#209]
The motivation for this is to avoid having users consuming paid resources (geocoding quotas, etc.) for analysis that may ultimately be aborted because its requirements exceed the limits (caching, etc.) we have established.

The idea is, before executing an Analysis's SQL operations (in `DataService#queueAnalysisOperations`), to collect its requirements. 

To do so, each analysis node would have to provide SQL code to compute its requirements, 
possibly using requirement results from its input nodes, in a similar way as each node provides currently an SQL query (we'd need some mechanism to have each node pass accumulated requirements information to the next one).

The requirement-computing statements of all nodes would be serialized (as is done with the queries) and executed before the analysis operations (in the same batch).

If requirements are not approved (e.g. by calling some function in the
cartodb extension that checks the accumulated requirements and approves/rejects them) the sequence would be aborted before executing any of the analysis operations.

We'd need to define which requirements must be estimated by each node, for example 
**caching space** (e.g. measured in number of rows and estimated row size in MB), 
**quotas** (for each of the data-services, geocoding, etc.), ... perhaps even CPU time.

The estimation of requirements might use query planner information and/or PG stats.
# UI interaction

As described above, the requirements checking would be easy to implement, but it might be more interesting to provide the requirements checking as a separate service, so that the UI could obtain the requirements and limits-approval before executing an analysis. This way the UI could, for an approved analysis, inform the user about the quotas to be consumed before the user confirms its execution.

**Comment by jgoizueta** [comment]
cc @rafatower @ethervoid  @rochoa @javisantana 

I'd appreciate some feedback from you, do you think we could start considering/discussing this?

**Comment by javisantana** [comment]
@rochoa and I  have been talking a little bit about this, the proposal was to tag every analysis with:

```
CPU - O(n)
CPUx2 - O(n*logn)
CPUxN - O(n^2)
IO
IOx2
...
MEM
MEMx2
...
```

So we know more or less the complexity of each analysis and we can guesstimate stuff based on those tags.

**Comment by jgoizueta** [comment]
After taking a deeper look at how camshaft works, and having in mind that we intend to find a pragmatic initial solution to prevent analysis that would clearly be over limits, I propose to do things differently, not through serialized SQL code.

I would execute requirements estimation (and possibly checking its limits and aborting) when the analysis is initially prepared by `Factory` (`lib/workflow/facctory`) `create` method.

This function create `Node` objects for all the nodes in the analysis and for each one:

* It sets the last updated time for the node using the SQL function `CDB_QueryTables_Updated_At`.
* It sets the name and types of the columns of  a node's result by issuing a `LIMIT 0` query to the database.
* It creates the (empty) cache table if necessary.

Each node is processed after their children (dependencies) by a combination of recusivity and `async.mapSeries`, so this should allow us to use requirements data from a node sources if necessary.

Checking the requirements here will give us more flexibility.

The next step will be to define the Node API to perform the requirements estimation/checking and modify Factory create to use that API.
