### ISSUE TITLE
Changes on 'Sequential Connect with lines Analysis'

### ISSUE THREAD

**Issue by hacheka** [CartoDB/camshaft#223]
In the builder and due to the issue https://github.com/CartoDB/cartodb/issues/10482 the `sequential connect with lines` analysis has been changed.

From now on, the `order` field is mandatory, not optional. It should be changed also in the Camshaft reference `line-sequential` JSON properties, to synchronise the builder UI and the analysis definition. `order-column` and `order-type` should be not marked as optional.

@dgaubert @xavijam

**Comment by xavijam** [comment]
Great, I feel it is not urgent @dgaubert. 💋

**Comment by dgaubert** [comment]
Hey @hacheka, are we talking about `routing-sequential` or `line-sequential` or both analyses?

**Comment by hacheka** [comment]
We're talking about `line-sequential`

My bad, I was checking an outdated reference when I wrote the description.
