### ISSUE TITLE
Range filter should be able to limit the amount of results

### ISSUE THREAD

**Issue by rochoa** [CartoDB/camshaft#24]
That requires sorting as well.

**Comment by rochoa** [comment]
cc @saleiva

**Comment by saleiva** [comment]
is limit + ORDER BY XXX DESC/ASC, remember :)

2016-05-11 17:53 GMT+02:00 Raul Ochoa <notifications@github.com>:

> cc @saleiva <https://github.com/saleiva>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/camshaft/issues/24#issuecomment-218503376>
>



-- 
Sergio Alvarez Leiva

**Comment by rochoa** [comment]
This was superseded by #75.
