### ISSUE TITLE
[node-v6] Node v6 LTS support

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/camshaft#247]
Support for Node 0.10.x has ended in October 2016. We need to migrate to the latest Node LTS version (v6.9.1)

**Comment by rochoa** [comment]
> https://github.com/CartoDB/camshaft/pull/248#issuecomment-273446306

True that.

**Comment by dgaubert** [comment]
On it!

**Comment by dgaubert** [comment]
Closed by #248
