### ISSUE TITLE
[CR] Add multiple categorized results option to "closest" analysis

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/camshaft#256]
As requested by customer

https://github.com/CartoDB/camshaft/pull/255

**Comment by AbelVM** [comment]
Added categorization feature

**Comment by nygeog** [comment]
![screen shot 2017-02-14 at 9 58 44 am](https://cloud.githubusercontent.com/assets/2790599/22946050/48902e2c-f2c4-11e6-9c63-ee8b720c679d.png)

**Comment by AbelVM** [comment]
Is that a proof of its realiability? Or you're showing that this fails? :thinking:

**Comment by nygeog** [comment]
Sorry, that's showing what the UI might look like. It's just the current UI with a **COUNT** slider. We had to the show the client something. The current tool doesn't initiate when APPLY is hit.

**Comment by AbelVM** [comment]
:+1:

**Comment by dgaubert** [comment]
@rochoa can we use Analysis Viewer to do the acceptance phase?

**Comment by dgaubert** [comment]
Fixed in [0.52.0](https://github.com/CartoDB/camshaft/releases/tag/0.52.0)
