### ISSUE TITLE
Release speed boost for DO Camshaft Node

### ISSUE THREAD

**Issue by talos** [CartoDB/camshaft#259]
## Summary

This is an issue to prioritize merge of https://github.com/CartoDB/camshaft/pull/254.

That PR updates `data-observatory-measure.js` to take advantage of `obs_getdata/obs_getmeta` to have some serious performance improvements.  This is a drop-in replacement that does not require any UI changes.

## Why we are doing this

- Performance in the existing analysis interface is very slow, on the order of 20-30QPS.
- New dataservices/observatory functions are already deployed so we can use much faster methods for obtaining Observatory data

## Requirements

None (https://github.com/CartoDB/dataservices-api/pull/339 has been merged and deployed)

## Statistics

test case | old time | new time | old qps | new qps | speedup
--- | --- | --- | --- | --- | ---
get population for 1000 US census tract polygons | 48.6s | 1.7s | 20.5 | _588_ | *28x*
get median income for 1000 US points | 47.2s | 0.2s | 21.1 | _5000_ | *236x*
get population density for 1000 US points | 47.2s | 0.2s | 21.1 | _5000_ | *236x*

**Comment by talos** [comment]
CC @rochoa here's the ticket to prioritize #254

**Comment by ethervoid** [comment]
@talos could you please add some acceptance test for this issue? I want to test it thoroughly in staging before I put in production :)

Thank you!

**Comment by talos** [comment]
@ethervoid By acceptance tests, do you mean new tests that have to be run by hand to confirm we can merge? Where is that file?

If so, they don't change -- as mentioned above:

> This is a drop-in replacement that does not require any UI changes.

If this works, nothing should be different at all.

It should be faster, but I don't know if that's something we note.

**Comment by ethervoid** [comment]
Yes, some steps to be sure everything works as intended with the deploy, for example to check the performance. I know this is just a "replace" but I want to be sure everything goes smooth :)

**Comment by talos** [comment]
Makes sense!  @ethervoid (and cc @michellemho for the example)

### Acceptance (polygon)

You should already be logged in as a user who has access to the Observatory and available credits.

1. Make a new map
2. Choose "Create Empty Map"
3. Zoom to "Brooklyn, NY" on the map.
4. Zoom to zoom level 15
5. Click on the layer on the left panel in order to add a geometry
6. Draw a small size rectangle in the area:

<img width="1368" alt="screen shot 2017-02-16 at 11 08 50 am" src="https://cloud.githubusercontent.com/assets/415831/23029518/d5e562b8-f438-11e6-92ae-9bec257608fa.png">

7. Add the polygon
8. Return to the layer panel to add an analysis
9. Add "Enrich from Data Observatory" to the layer
10. Type "totalpop" for "New col. name", choose "United States" for country, "Age and Gender" for "measurement", and "Total Population" for "Segments".
11. Click "Apply"
12. Switch to table view and confirm the column has been added with a population column:

<img width="1381" alt="screen shot 2017-02-16 at 11 12 28 am" src="https://cloud.githubusercontent.com/assets/415831/23029524/da15f9d8-f438-11e6-85f9-16d3d784fdf3.png">

### Acceptance (point)

You should already be logged in as a user who has access to the Observatory and available credits.

1. Make a new map
2. Choose "Create Empty Map"
3. Zoom to "Brooklyn, NY" on the map.
4. Click on the layer on the left panel in order to add a geometry
5. Add several points:

<img width="1201" alt="screen shot 2017-02-16 at 11 17 47 am" src="https://cloud.githubusercontent.com/assets/415831/23029761/9434132c-f439-11e6-9e88-31472e36a251.png">

6. Return to the layer panel to add an analysis
6. Add "Enrich from Data Observatory" to the layer
8. Type "income" for "New col. name", choose "United States" for country, "Income" for "measurement", and "Median Household Income for the past 12 Months" for "Segments".
11. Click "Apply"
12. Switch to table view and confirm the column has been added with an income column:

<img width="1373" alt="screen shot 2017-02-16 at 11 19 28 am" src="https://cloud.githubusercontent.com/assets/415831/23029844/cd1d32cc-f439-11e6-9521-bf2464ec1476.png">

**Comment by ethervoid** [comment]
Cool, great acceptance! Thank you :)

**Comment by ethervoid** [comment]
Done acceptance by myself in staging cloud, I'm not the one doing the changes just the deployment. Everything work as intented

**Comment by ethervoid** [comment]
Deployed :)

**Comment by rochoa** [comment]
Kudos on your first one! :)

**Comment by ethervoid** [comment]
Thank you!!! :D :D
