### ISSUE TITLE
Run ANALYZE on cache tables upon creation

### ISSUE THREAD

**Issue by rafatower** [CartoDB/camshaft#260]
Run ANALYZE upon creation of cache tables in order to have better stats.

One reason to want to do it is to have better row count estimates. See https://github.com/CartoDB/cartodb/pull/11480#issuecomment-279403618

Furthermore, it helps the query planner take better decisions and is meant to be run eventually anyway.

Update: PR here: https://github.com/CartoDB/camshaft/pull/263

**Comment by rafatower** [comment]
### Acceptance
- Import or create a dataset of 30 points
- Run an analysis on that dataset that produces a cache table. E.g: [buffer](https://github.com/CartoDB/camshaft/blob/44bfe26100a49c394c8cca2fc51e42050ffdd15a/lib/node/nodes/buffer.js#L15)
- Check that the estimated number of rows is close to 30 (1% error margin). For that you can connect to the user db and locate the last analysis:
```
# select * from cdb_analysis_catalog order by updated_at desc limit 1;
-[ RECORD 1 ]------+------------------------------------------------------------------------------------------------------------------
node_id            | 4df056f2b3f559e0f9040c690c7d1a15920b1780
analysis_def       | {"type":"buffer","source":"49a1ae803609d3f8550b0d80a71cf6a417b354e0","radius":500,"isolines":1,"dissolved":false}
input_nodes        | {49a1ae803609d3f8550b0d80a71cf6a417b354e0}
status             | ready
created_at         | 2017-02-14 13:49:50.205134+00
updated_at         | 2017-02-14 13:49:51.004178+00
used_at            | 2017-02-14 13:49:51.9326+00
hits               | 2
last_used_from     | 4df056f2b3f559e0f9040c690c7d1a15920b1780
last_modified_by   | 657e355a-f104-4249-b339-7a6bee76c3ee
last_error_message | 
cache_tables       | {analysis_2f13a3dbd7_4df056f2b3f559e0f9040c690c7d1a15920b1780}
username           | cdb
```

then run this EXPLAIN on the cache table:
```
# explain select * from analysis_2f13a3dbd7_4df056f2b3f559e0f9040c690c7d1a15920b1780;
                                                    QUERY PLAN                                                    
------------------------------------------------------------------------------------------------------------------
 Seq Scan on analysis_2f13a3dbd7_4df056f2b3f559e0f9040c690c7d1a15920b1780  (cost=0.00..83.09 rows=30 width=588)
(1 row)
```
(check the rows value is close to 30).

### Bonus acceptance
- Import a dataset with a few thousand rows of variable size (e.g: polygons of different complexities)
- Run a buffer analysis
- Check the row estimate again. It is expected to be less accurate than in the former case.

**Comment by rafatower** [comment]
Changes will go around these lines: https://github.com/CartoDB/camshaft/blob/44bfe26100a49c394c8cca2fc51e42050ffdd15a/lib/service/database.js#L323

**Comment by rafatower** [comment]
@jgoizueta I wrote the "bonus acceptance" to my future self, please take it as just "nice to have". Please don't hesitate to ping me if you need anything :)

**Comment by jgoizueta** [comment]
Acceptance results: (staging tests)

For a cached analysis based on a 27-point table the explain estimate is 27 rows (exact). It used to be 580 before applying this changes.

Then I checked with a 5187 polygons dataset (Canada Census subdivisions). The estimate is now 5187, but it is also 5187 every time without the changes.

For other 62136-point table the estimation was also exact before this changes, while small tables, either points or polygons used to had bad estimates (504 for 223 points, 180 for 18 large polygons).

@rafatower: thanks and apologies for this taking too long

**Comment by rafatower** [comment]
> @rafatower: thanks and apologies for this taking too long

No problem at all, and thanks for the acceptance :)

Just a quick note on your acceptance tests: for tables above 30 rows. This is the default config for the autovacuum process:
```
postgres=# show autovacuum_analyze_threshold ;
 autovacuum_analyze_threshold 
------------------------------
 50
(1 row)
```

that means that the ANALYZE will eventually run in background. If it is not run yet then you could see very disparate results as stats are not available yet. There's an inherent "race condition", so to say, if you rely on stats (I ran my previous batch of tests disabling the autovacuum process altogether).

E.g:
```
postgres=# CREATE TABLE test_row_estimation AS SELECT id, random() AS value FROM generate_series(1,5000) AS id LIMIT 0;
SELECT 0
postgres=# INSERT INTO test_row_estimation SELECT id, random() AS value FROM generate_series(1,5000) AS id; EXPLAIN SELECT * FROM test_row_estimation;
INSERT 0 5000
                               QUERY PLAN                               
------------------------------------------------------------------------
 Seq Scan on test_row_estimation  (cost=0.00..45.14 rows=5712 width=12)
(1 row)

postgres=# select count(1) from test_row_estimation ;
 count 
-------
  5000
(1 row)

-- If you just wait a little for the autovacuum process to pass by... look for this trace LOG:  automatic analyze of table "postgres.public.test_row_estimation":
postgres=# EXPLAIN SELECT * FROM test_row_estimation;
                               QUERY PLAN                                
-------------------------------------------------------------------------
 Seq Scan on test_row_estimation  (cost=0.00..85.00 rows=5000 width=12)
(1 row)
```
