### ISSUE TITLE
Georeference should accept more than one column to compose the street address

### ISSUE THREAD

**Issue by jorgesancha** [CartoDB/camshaft#267]
Currently the Georeference by street address [only accepts one parameter for the street address](https://github.com/CartoDB/camshaft/blob/master/lib/node/nodes/georeference-street-address.js#L9) However, it is often the case where users data hold the street address in different columns (street type, address, number...).

The analysis should accept a template for the address param to match the UI described in CartoDB/cartodb/issues/11662.

cc @saleiva @noguerol @xavijam @rochoa

**Comment by jorgesancha** [comment]
adding to TODO in Engine board

cc/ @rochoa

**Comment by rochoa** [comment]
The final UI is ready. We can start the development based on that.

**Comment by jorgesancha** [comment]
Yes please!! This is quite urgent, team
