### ISSUE TITLE
Closest analysis should have limits

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/camshaft#290]
The closest (nearest) analysis doesn't have limits and it should be limited similarly as the `line-source-to-target` analysis.

This analysis, applied to moderate-sized input can render huge outputs (regarding number of rows).

I've found a couple of cases of large analysis cache tables:
* 71GB for a case where inputs had 13665 rows each
* 40GB for 3846 by 50739 rows inputs

cc @mbforr @ztephm

**Comment by jgoizueta** [comment]
Acceptance should consist deploying this to staging (create a Windshaft-cartodb branch using camshaft from this branch?)
Then creating a map with two layers with more than 10000 points (the same dataset can be used for both layers) and adding a "find nearest" analysis using the layers (without grouping). The analysis should fail with a message about "too many result lines"

**Comment by rafatower** [comment]
Bonus: I tested with a table with 999 rows and it worked as expected (no error message and analysis worked)

**Comment by rafatower** [comment]
Ready to be deployed: https://github.com/CartoDB/Windshaft-cartodb/releases/tag/3.9.4
