### ISSUE TITLE
Connect With Lines analysis result is in WGS84 projection units instead of meters

### ISSUE THREAD

**Issue by ztephm** [CartoDB/camshaft#295]
@rafatower

### Context

* S/B 11562737

Two different Connect with lines analyses in same map return results in different units.

This is happening because we apply the Postgis ST_Length() [like this in our line-sequential.js code](https://github.com/CartoDB/camshaft/blob/master/lib/node/nodes/line-sequential.js#L36). We are using the_geom column without transforming it to `geography` type. This means that the length is units of WGS84 projection instead of meters.

Can we modify so result is in meters?

### Steps to Reproduce

1. Create a map from [this origin_point dataset](https://team.carto.com/u/stephaniemongon/dataset/origin_point).
2. Add [this close_point dataset](https://team.carto.com/u/stephaniemongon/dataset/close_point) as another layer.
3. Add a Connect with Lines analysis to origin_point layer. 
4. Apply these analysis parameters: 
  * Source = origin_point
  * Type = To Source
  * Target = close_point
  * Closest = To closest

### Current Result
Analysis adds a "length" column to origin_point layer. Length number is 240.585781997043.

* I verified this was in meters by applying ST_Distance in the origin_point dataset:
  `SELECT ST_Distance(origin_point.the_geom::geography,close_point.the_geom::geography) AS dist FROM origin_point, close_point`

  SQL query result was also 240.585781997.

 
### Expected result
Mine was expected result, client's is not.

Problem is in client's map, when he uses Connect with lines analysis for these points he gets a value in km:  
.240586

  * client: ![client](https://cloud.githubusercontent.com/assets/1779444/23526499/4200562e-ff60-11e6-85b2-fdb191b0f3b7.png)

  * mine: ![mine](https://cloud.githubusercontent.com/assets/1779444/23526505/4481f33a-ff60-11e6-9b3a-d9a42bfbfc2f.png)

### Browser and version

Chrome 56.0.2924.87

 
### .carto file

My test: 
[close_point map (on 2017-03-02 at 20.48.48).zip](https://github.com/CartoDB/support/files/815060/close_point.map.on.2017-03-02.at.20.48.48.zip)

Client's is in S/B ticket for data privacy.

**Comment by rafatower** [comment]
I do think this is more of a product issue than the analysis itself. On one hand, letting the user know the units of the length. OTOH and potentially letting the user choose the units or stick to a standard (meters or whatever) as suggested in the original request.

**Comment by saleiva** [comment]
already opened a while ago cc/ @noguerol @jorgesancha https://github.com/CartoDB/cartodb/issues/12084
