### ISSUE TITLE
Analysis with multiple measures fails when 0 < credits < (no_rows x measurements)

### ISSUE THREAD

**Issue by rafatower** [CartoDB/camshaft#302]
The new analysis implemented in #297 fails when the user has enough credits to start the analysis but not enough to get the measurements for all rows.

This is due to the fact that the DS API throws an exception as soon as the user runs out of quota, causing whatever transaction it is run within to fail.

Here is a sample trace from staging:

```
May 22 16:46:05 dbd03-st postgres[5008]: [25-1] 2017-05-22 16:46:05 GMT postgres cartodb_staging_user_fef64064-3754-40b4-9032-6f7d6cd95edf_db [unknown] ERROR:  Exception: You have reached the limit of your quota
May 22 16:46:05 dbd03-st postgres[5008]: [25-2] 2017-05-22 16:46:05 GMT postgres cartodb_staging_user_fef64064-3754-40b4-9032-6f7d6cd95edf_db [unknown] CONTEXT:  Traceback (most recent call last):
May 22 16:46:05 dbd03-st postgres[5008]: [25-3] #011  PL/Python function "obs_getdata", line 16, in <module>
May 22 16:46:05 dbd03-st postgres[5008]: [25-4] #011    raise Exception('You have reached the limit of your quota')
May 22 16:46:05 dbd03-st postgres[5008]: [25-5] #011PL/Python function "obs_getdata"
May 22 16:46:05 dbd03-st postgres[5008]: [25-6] 2017-05-22 16:46:05 GMT postgres cartodb_staging_user_fef64064-3754-40b4-9032-6f7d6cd95edf_db [unknown] STATEMENT:  SELECT * FROM cdb_dataservices_server.obs_getdata ($1::text, $2::text, $3::public._geomval, $4::json, $5::bool)
```

The code triggering such exception is here: https://github.com/CartoDB/dataservices-api/blob/d7fad6d8d349155b57e8caf83fd677df0fdc583e/server/extension/sql/110_data_observatory_augmentation.sql#L609

For other DS API functions what's implemented is a set of exception-safe functions in the client side.

The discussion and details of exception-safe functions are here:

https://github.com/CartoDB/dataservices-api/blob/development/doc/internal/exception_safe.md
https://github.com/CartoDB/dataservices-api/issues/314

and their integration within camshaft:

https://github.com/CartoDB/camshaft/issues/242
https://github.com/CartoDB/camshaft/pull/243

You can get a list of such functions by running this on a user db:
```
\df cdb_dataservices_client.*_exception_safe
```

there is indeed an exception-safe version of `OBS_GetData`:
```
cartodb_staging_user_b19a3b93-9826-4cf1-8c69-60d8871a31cc_db=> \df cdb_dataservices_client.*obs_getdata*
                                                                                         List of functions
         Schema          |            Name             |       Result data type       |                                        Argument data types                                         |  Type  
-------------------------+-----------------------------+------------------------------+----------------------------------------------------------------------------------------------------+--------
 cdb_dataservices_client | _obs_getdata                | TABLE(id text, data json)    | username text, organization_name text, geomrefs text[], params json                                | normal
 cdb_dataservices_client | _obs_getdata                | TABLE(id integer, data json) | username text, organization_name text, geomvals geomval[], params json, merge boolean DEFAULT true | normal
 cdb_dataservices_client | _obs_getdata_exception_safe | TABLE(id text, data json)    | geomrefs text[], params json                                                                       | normal
 cdb_dataservices_client | _obs_getdata_exception_safe | TABLE(id integer, data json) | geomvals geomval[], params json, merge boolean DEFAULT true                                        | normal
 cdb_dataservices_client | obs_getdata                 | TABLE(id text, data json)    | geomrefs text[], params json                                                                       | normal
 cdb_dataservices_client | obs_getdata                 | TABLE(id integer, data json) | geomvals geomval[], params json, merge boolean DEFAULT true                                        | normal
(6 rows)
```

However, we implemented this with row-by-row service functions in mind. We need to check if this approach works for this case and otherwise figure out a different approach.

cc/ @dgaubert @nobuti @jorgesancha

**Comment by dgaubert** [comment]
Hey @rafatower 

I've deployed a camshaft version using **exception_safe** functions of `OBS_GetData`. Do you think we should close this issue?

**Comment by rafatower** [comment]
I'd run the faulty scenario before closing this issue to make sure the changes actually fix it.

**Comment by dgaubert** [comment]
I've tried to run a faulty scenario but not sure how to do it. Do you have a STR for that??

**Comment by rafatower** [comment]
This somehow depends on the code Buti is writing but anyway:

## Acceptance
1. Set up a user with some obs credits
1. Try to run an obs with multiple measures analysis (new UI) on a table with `n_rows > n_credits`

### Expected result
The analysis should provide observatory measures up to `n_credits`

### Current result
The analysis fails half way, not returning anything.

**Comment by dgaubert** [comment]
Hey, I'm trying to pass acceptance test but I got the following error:
```
{"error":["PL/Proxy function cdb_dataservices_client._obs_getavailabletimespans(7): Got too many fields from remote end"]}
```
while the UI is fetching data from DO to fill the form:
```
SELECT * FROM OBS_GetAvailableTimespans((SELECT ST_SetSRID(ST_Extent(the_geom), 4326) FROM (SELECT * FROM beach_flats_extended_1) q), NULL, 'us.census.lodes.jobs_less_than_high_school', NULL) denoms WHERE valid_numer IS TRUE
```

Can anyone shed some light here?

**Comment by rafatower** [comment]
If it is in production I wouldn't expect that issue :S

**Comment by dgaubert** [comment]
Environment: `staging cloud` (api01-st, api02-st, api04-st)
User: `mamut-st`

**Comment by rafatower** [comment]
Are the bounds of your table data (extent) within some region covered by the observatory?

**Comment by dgaubert** [comment]
California -> Santa Cruz -> Downtown. So I'd say yes. rigth?

**Comment by rafatower** [comment]
to check the credits:
```
select * from cdb_dataservices_client.cdb_service_quota_info();
    service     | monthly_quota | used_quota | soft_limit |     provider     
----------------+---------------+------------+------------+------------------
 isolines       |             0 |          0 | f          | mapzen
 hires_geocoder |           400 |          0 | f          | mapzen
 routing        |            50 |          0 | f          | mapzen
 observatory    |             3 |      46606 | t          | data observatory
(4 rows)
```

**Comment by rafatower** [comment]
Mind that configs may be cached for a while: https://github.com/CartoDB/dataservices-api/issues/349#issuecomment-285013037

**Comment by jgoizueta** [comment]
```

**Comment by jgoizueta** [comment]
I found some odd behaviour:

I setup a user, in staging, with 10000 DO credits; 
then added a DO (multi-measurement) analysis  with a single measurement and on a 1456-row table, (so that the UI didn't prevent me from doing the analysis) the  but before confirming I changed the DO credits to 1000.

Even though a warning like this appeared:

![screen shot 2017-06-19 at 14 39 48](https://user-images.githubusercontent.com/5909/27288513-3c7c735c-5507-11e7-8d2e-a35f26762f11.png)

All rows were augmented (with non-NULL values, except for 25 rows which didn't have geometry, and quota in excess of the available quota was used up (and the account didn't have a soft limit):

```
select * from cdb_dataservices_client.cdb_service_quota_info();
    service     | monthly_quota | used_quota | soft_limit |     provider
----------------+---------------+------------+------------+------------------
 isolines       |            10 |          0 | f          | heremaps
 hires_geocoder |           100 |          0 | f          | mapzen
 routing        |           100 |          0 | f          | mapzen
 observatory    |          1000 |       1431 | f          | data observatory
(4 rows)
```

**Comment by rafatower** [comment]
If you look at the dataservices-api code referenced above, I think the behavior you describe makes sense and that it basically means that we have to fix it there rather than in camshaft. I'd take the acceptance test as failed.

**Comment by jgoizueta** [comment]
I repeated the test a couple of times with the same result: either the UI prevent the analysis or it completes reagardless of the available quota

**Comment by rochoa** [comment]
Considering https://github.com/CartoDB/bigmetadata/issues/230, IMO, this no longer makes sense. Closing it, but feel free to reopen if you think the opposite.
