### ISSUE TITLE
Filter by column value analysis runs incorrect(ly labeled?) filters

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/camshaft#309]
The options for a filter by column value analysis on a number field are:

- between
- is equal to
- is greater than
- is less than

In addition to not offering the often used "is greater than or equal to" and "is less than or equal to" options, the "is greater than" and "is less than" analyses actually use a `>=` and `<=` operators in the SQL (instead of the proper-for-their-labels `>` and `<`), so they _are_ actually running "greater than or equal to" and "less than or equal to"!

As it stands, then, there's no way to run a is greater than or is less than analysis.

Proposed resolution would be to re-label the ones that are there correctly, and add new ones covering the other cases:

- between
- is equal to
- is greater than `>`
- is greater than or equal to `>=`
- is less than `<`
- is less than or equal to `<=`

**Comment by andrewbt** [comment]
Could the logic be in here? https://github.com/CartoDB/camshaft/blob/master/lib/filter/range.js

**Comment by nygeog** [comment]
So I was helping user today using Filter by Column Value in the Builder and realized `greater than` the value `0` didn't work. It kept all the zero values. I randomly mentioned this to @andrewbt and he mentioned this issue. So I'm raising this issue as there should be **no ambiguity** as to what **greater than** means. **greater than** != **greater than or equal to** they are completely different. See https://en.wikipedia.org/wiki/Inequality_(mathematics)

CC @kevin-reilly

**Comment by andrewbt** [comment]
I think this would be a great candidate for the new response team ( @jorgesancha @jsanz ?)

**Comment by kevin-reilly** [comment]
I put this in the response teams backlog.

cc: @noguerol

**Comment by nygeog** [comment]
Thanks! Will follow this Issue and get back to lead when fixed!

**Comment by brittanymicek** [comment]
@nygeog @andrewbt I hope this helps. I didn't test it.


'use strict';

var dot = require('dot');
dot.templateSettings.strip = false;

var betweenFilterTpl = dot.template('{{=it._column}} BETWEEN {{=it._min}} AND {{=it._max}}');
var equalToFilterTpl = dot.template('{{=it._column}} === {{=it._min}} AND {{=it.max}}');

var greaterEqualToMinFilterTpl = dot.template('{{=it._column}} >= {{=it._min}}');
var lessEqualToMaxFilterTpl = dot.template('{{=it._column}} <= {{=it._max}}');

var greaterMinFilterTpl = dot.template('{{=it._column}} > {{=it._min}}');
var lessMaxFilterTpl = dot.template('{{=it._column}} < {{=it._min}}');

var filterQueryTpl = dot.template('SELECT * FROM ({{=it._sql}}) _camshaft_range_filter WHERE {{=it._filter}}');
var dateColumnTpl = dot.template('date_part(\'epoch\', {{=it._column}})');

function Range(column, filterParams) {
	this.column = column.name;
	this.columnType = column.type;

	if (!Number.isFinite(filterParams.min) && !Number.isFinite(filterParams.max)) {
		throw new Error('Range filter expected at least one value for min or max numeric params');
	}
	this.min = filterParams.min;
	this.max = filterParams.max;
}

module.exports = Range;

Range.prototype.sql = function(rawSql) {
	var _column = this.column;
	if (this.columnType === 'date') {
	_column = dateColumnTpl({ _column: _column });
	}

var minMaxFilter;
if (Number.isFinite(this.min) && Number.isFinite(this.max)) {
	minMaxFilter = betweenFilterTpl({
		_column: _column,
		_min: this.min,
		_max: this.max
		});
	} else if (Number.isFinite(this.min) && Number.isFinite(this.max)) {
		minMaxFilter = equalToFilterTpl({ _column: _column, _min: this.min, _max: this.max});
	} else if (Number.isFinite(this.min)) {
		minMaxFilter = greaterEqualToMinFilterTpl({ _column: _column, _min: this.min });
	} else if (Number.isFinite(this.max)) {
		minMaxFilter = lessEqualToMaxFilterTpl({ _column: _column, _ max: this.max});
	} else if (Number.isFinite(this.min)) {
		minMaxFilter = greaterMinFilterTpl({ _column: _column, _min: this.min});
	} else {
		minMaxFilter = lessMaxFilterTpl({ _column: _ column, _max: this.max});
	}
	return filterQueryTpl({
		_sql: rawSql,
		_filter: minMaxFilter
		});
};
https://github.com/CartoDB/camshaft/files/1114092/camshaftFilterByColumnCARTO.txt

**Comment by noguerol** [comment]
As noted by @saleiva, much better if we only use text labels:

1. Between
2. Equal to
3. Greater than
4. Greater than or equal to
5. Less than
6. Less than or equal to

**Comment by dgaubert** [comment]
Moving back to development. We changed the behavior of range filter breaking backward compatibility.

**Comment by rubenmoya** [comment]
In production 🚀
