### ISSUE TITLE
Filter NULL geometries to create the geomvals in data-observatory nodes

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/camshaft#311]
Related CartoDB/observatory-extension#290

We need to filter the NULL geometries in the data-observatory node query in order to avoid create empty `geomvals` that could interfere with the proper functioning of the observatory function.

So the way to deal with this in to remove NULL values [here](https://github.com/CartoDB/camshaft/blob/master/lib/node/nodes/data-observatory-measure.js#L34) and [here](https://github.com/CartoDB/camshaft/blob/master/lib/node/nodes/data-observatory-multiple-measures.js#L126)

**Comment by ethervoid** [comment]
### Acceptance

Import [this dataset](https://github.com/CartoDB/camshaft/files/1077926/test_dataset.csv.zip) and try to reproduce this analysis:

![Image of Yaktocat](https://user-images.githubusercontent.com/2932575/26947330-57a517ce-4c60-11e7-87c1-696d46376935.png)

This time you should get values in the augmented columns

**Comment by dgaubert** [comment]
It worked!

![screen shot 2017-06-15 at 16 56 56](https://user-images.githubusercontent.com/1936888/27187516-b763c22e-51eb-11e7-81a2-bc95d530c8d7.png)

**Comment by dgaubert** [comment]
Also it works in the old form:

![screen shot 2017-06-15 at 17 11 35](https://user-images.githubusercontent.com/1936888/27188279-f3aad4a0-51ed-11e7-909d-0b379e02d575.png)
