### ISSUE TITLE
Add limit to DO by the number of vertex of the dataset and/or rows

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/camshaft#314]
DO behaves badly in performance if deals with polygons but if those polygons are huge it's even worse. For example, a 381 rows dataset generates a 7M query which takes about 1 hour to end so we have 1 core doing that query.

What if we limit the DO analysis for Huge polygons? For example something like:
```
cartodb_dev_user_23c39318-a446-4c62-ab2c-32e78757ba19_db=# SELECT sum(ST_NPoints(the_geom)) FROM job_automation_risk_merged;
  sum
--------
 225214
(1 row)
```

It'd be great to use the stats for this but the only stats we have are the PostGIS ones and only have the number of features.

**Comment by ethervoid** [comment]
Or even better to use the AVG:
```
cartodb_dev_user_23c39318-a446-4c62-ab2c-32e78757ba19_db=# SELECT avg(ST_NPoints(the_geom)) FROM job_automation_risk_merged;
         avg
----------------------
 591.1128608923884514
(1 row)
```

to check the average number of vertex

**Comment by rochoa** [comment]
@ethervoid, this is an interesting topic.

Should external users of DO be responsible for limiting the input? Yes, but we need to define those limits, and yet still, the DO should take care of the final validation, error handling/reporting, and limits.

Obviously, we can keep improving camshaft to deal with this situations, but at the end, it's a DO responsibility to impose and verify these limits. What are your thoughts on the topic?

**Comment by ethervoid** [comment]
Yes, I agree we should provide the users what limits they should not pass because we're going to act in consequence.

Agree too with the statement that DO should take care of [validation of the data](https://github.com/CartoDB/cartodb-management/issues/4965) and error handling/reporting.

For the limit topic, I agree but with some nuances. We have to implement those limits in DO, we have to find a way to make it easy to add/remove/modify and that doesn't need to make a full deploy. But in the meantime, we have to limit or try to limit some huge analysis that could hurt our infrastructure like this one. 

For me, using the current limit feature in camshaft is a low-hanging fruit that could make as improve the stability of the platform.

We have a lot of work to do in the DO and in DS: error handling/reporting, decoupling of the providers in the case of DS, limits included in the DO, etc.

**Comment by rochoa** [comment]
> For me, using the current limit feature in camshaft is a low-hanging fruit that could make as improve the stability of the platform.

Totally agree on that.

**Comment by ethervoid** [comment]
This was already done
