### ISSUE TITLE
DO: Error augmenting with text columns

### ISSUE THREAD

**Issue by javitonino** [CartoDB/camshaft#315]
STR
1. Create an empty map
2. Create a point in Spain
3. Add a DO analysis, select "Proper name of prov" as the measure
4. Run the analysis

You get an error `Analysis A1 failed: invalid input syntax for type numeric: "Toledo"`. This happens with both DO analyses (single/multi measure).

I have not confirmed this is a camshaft issue (it could be in the extension), but I feel like this is related to [this numeric cast](https://github.com/CartoDB/camshaft/blob/f624d98a7658654abeb1b4dd2e13c9426fd9951e/lib/node/nodes/data-observatory-multiple-measures.js#L84). In any case, more investigation is needed.

cc @juanignaciosl

**Comment by noguerol** [comment]
Guys, i've copied the ticket in /bigmetadata in order to be in the milestone. I close this one.
