### ISSUE TITLE
Force "merge" analysis to be cached

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/camshaft#347]
We found that under some circumstances a "merge" analysis could have a high cost in performance terms.

**Comment by dgaubert** [comment]
We aren't going to implement this. Caching `merge` analysis is worse than having some scenarios with performance issues. Further info: https://github.com/CartoDB/camshaft/pull/348

**Comment by ramiroaznar** [comment]
cc @CartoDB/support for awareness
