### ISSUE TITLE
Perfect Sales Territory - Create Augment with DO measure Analysis

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/camshaft#37]
Create a camshaft analysis that will take all points/regions and augment them with a measure from the data observatory.

@talos

**Comment by rochoa** [comment]
Can we start using DO for this analysis? We could help you working on this issue.

**Comment by talos** [comment]
I'm going to get started on this this week -- will reach out as things get underway.

**Comment by stuartlynn** [comment]
Hey guys. Looks like this has been done by @dgaubert ! Which is awesome!
https://github.com/CartoDB/camshaft/pull/45

Me and @talos where chatting at the end of last week and it occurred to us that we aren't sure how the builder / camshaft can get access to the metadata for the data observatory.

Ideally in the builder, instead of entering in a name of a measure we would want to present the user with a dropdown list of available data observatory measures based on 

- The geometry type of the previous analysis step 
- The geographic bounds of the previous analysis step 
- A user specified time range

Right now we would have to hardcode these measures in to an ENUM within camshaft but it really should be dynamic based on the factors above. Is there away that camshaft can perform dynamic queries at execution and use these to return options? Or is this something that will happen in the front end builder code?

Don't think we need to have this in place right now but it would be good to start thinking about.

**Comment by rochoa** [comment]
I guess we will need help from @xavijam here.

I'm not a big fan of the ENUM hardcoded value here because that means that each time we add a measure to DO we need to publish a new camshaft + camshaft-reference + windshaft-cartodb version, and release them to production.

**Comment by talos** [comment]
Agreed!  I think if at all possible, we should try to keep ENUMs with OBS data in them out of the initial release.

**Comment by stuartlynn** [comment]
Yeah not a fan of hard coded ENUMS either, would love to find a way for this to interface with the DO

**Comment by xavijam** [comment]
Wouldn't it make sense to have a API that provides all the DO metadata for the user? If that fits the gap, we could create whatever we want in the UI. But in any case I'd like to hear/check @CartoDB/design and @javisantana first.

**Comment by talos** [comment]
Yep, that's something we've been discussing internally -- we've already generated a simplified version of the metadata tables that could be accessed by the UI through a function.  Probably the simplest implementation would be one additional observatory-extension function that pulls down that table or filters for relevant parts of it.

**Comment by javisantana** [comment]
in the meantime we could hardcore them in the editor

**Comment by talos** [comment]
Not sure why this is still open.
