### ISSUE TITLE
Perfect Sales Territory - Generate example data

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/camshaft#39]
Need to generate a list of fake customers

**Comment by andrewxhill** [comment]
are you thinking of having example data accessible to camshaft or something else?

**Comment by stuartlynn** [comment]
No just having an example data set of customers that we can use in the demo

**Comment by andrewxhill** [comment]
try this one, https://team.cartodb.com/u/andrew/tables/customer_home_locations/map

**Comment by stuartlynn** [comment]
cool
