### ISSUE TITLE
Noise in the analysis logs

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/camshaft#396]
We have a function [`logError`](https://github.com/CartoDB/camshaft/blob/53334ba438192aff240e60c65600dfc83c2b49e2/lib/limits/context.js#L16-L20)  in the `LimitsContext` that expects as argument an `err` object with  [`message` and `code`](https://github.com/CartoDB/camshaft/blob/53334ba438192aff240e60c65600dfc83c2b49e2/lib/logging/logger.js#L41-L42) properties.

But, in some cases, like when checking if limits are defined in the configuration (e.g. [here](https://github.com/CartoDB/camshaft/blob/53334ba438192aff240e60c65600dfc83c2b49e2/lib/node/limits.js#L29)), we're passing a text instead. So in such cases the text message is lost in the log and we only have a very generic `"msg":"analysis:limits_error"` that doesn't provide any useful information.

Since many of the analysis node limits are not defined in the configuration there's a lot of those messages the logs.

We should:

* Fix the calls that pass a text, so it is not lost (e.g. `context.logError({message: 'Limit for input rows is not defined'});`).
* Reconsider if the messages about limits not configured are useful, remove them otherwise

**Comment by dgaubert** [comment]
cc @CartoDB/rt-managers for priorization

**Comment by ztephm** [comment]
Please prioritize this as `important`-level @juanrmn . Thank you.

**Comment by juanrmn** [comment]
I've opened a PR (https://github.com/CartoDB/camshaft/pull/399) about this. So far I've just fixed the calls to `logError`. About the usefulness of each message, I don't feel familiarized enough with the project to judge that, so all of them seem useful to me :slightly_smiling_face:. However, if you think that any of them should be deleted, please add comments to the PR and I'll do it.

**Comment by dgaubert** [comment]
Done https://github.com/CartoDB/Windshaft-cartodb/pull/1156
