### ISSUE TITLE
Filter rank analysis

### ISSUE THREAD

**Issue by rochoa** [CartoDB/camshaft#75]
Add new analysis to support filtering by a ranked column to pick top or bottom N elements.

**Comment by rochoa** [comment]
cc @javierarce

**Comment by rochoa** [comment]
@saleiva Does it make sense to _pick top 5 elements **aggregated by a category column**_?

Example: I want 5 best lap times by driver, if there are 10 different drivers I would get up to 50 laps.

**Comment by saleiva** [comment]
An option would be to have the GROUP BY option in the filter analysis

**Comment by saleiva** [comment]
Gonna take a look at the UI, and create an issue on main repo
