### ISSUE TITLE
Improve Centroid analysis to contain simple centroid

### ISSUE THREAD

**Issue by saleiva** [CartoDB/camshaft#77]
And to make the grouping optative.

![screen shot 2016-06-22 at 18 56 00](https://cloud.githubusercontent.com/assets/132149/16275603/060a0aec-38ab-11e6-95f7-64801445c3c8.png)

**Comment by rochoa** [comment]
My proposal is to have another analysis: `centroid`. It will have an optional `group_by`. OK?

**Comment by saleiva** [comment]
I'd prefer to have one box for both like designed. We should try to avoid
having 100s of different boxes on that modal in order to improve
findability.

2016-06-23 11:45 GMT+02:00 Raul Ochoa <notifications@github.com>:

> My proposal is to have another analysis: centroid. It will have an
> optional group_by. OK?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/camshaft/issues/77#issuecomment-228001423>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENaVDnPy6SNnhPhZ5JnkF8GZmkBYXks5qOlXSgaJpZM4I7_4l>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by rochoa** [comment]
I will rework a bit the `weighted-centroid` to make the group by optional.

cc @javierarce
