### ISSUE TITLE
Weighted Centroid seems to be not working correctly

### ISSUE THREAD

**Issue by saleiva** [CartoDB/camshaft#79]
Download this dataset.
https://team.cartodb.com/u/saleiva/tables/chicago_crimes_2014

I've created two fake columns for testing (crimes_value and crimes_value_2)
The centroids you get when using crimes_value column (all rows equal to 1) as weight is the same result you get when using cromes_value_2 (lots of rows equal to 2, the rest to 1).

cc/ @javisantana @rochoa @ohasselblad @stuartlynn

**Comment by stuartlynn** [comment]
Looking in to it now thanks for the heads up @saleiva

**Comment by javisantana** [comment]
with that amount of points and randomly distributed '2' and '1' I think is correct. Test it with two points table

**Comment by saleiva** [comment]
but the centers are exactly the same, that's very weird, don't you think?

**Comment by rochoa** [comment]
Try it with something like:

```sql
with points as (
  select (s * s) as s, st_makepoint(s,s) as the_geom from generate_series(1,2) s
)
select st_astext(cdb_crankshaft.CDB_WeightedMean(the_geom, s)) as the_geom
from points
```

And play with the `s` value from the CTE.

IMO it's working OK.

**Comment by javisantana** [comment]
@saleiva visually can be misleading (since there is snapping), did you test it matematically?

**Comment by saleiva** [comment]
lat/long values where the same at a quick sight

2016-06-23 12:16 GMT+02:00 javi santana <notifications@github.com>:

> @saleiva <https://github.com/saleiva> visually can be misleading (since
> there is snapping), did you test it matematically?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/camshaft/issues/79#issuecomment-228008134>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENWBrXbKYujXSQxciBE9WGRCF0UKaks5qOlzggaJpZM4I8Kgf>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by stuartlynn** [comment]
@saleiva When I try it they look different . Not by much but different
 
![screen shot 2016-06-23 at 9 47 59 am](https://cloud.githubusercontent.com/assets/209838/16305451/ed7a7f48-3927-11e6-9c16-7576b5696c17.png)
![screen shot 2016-06-23 at 9 47 46 am](https://cloud.githubusercontent.com/assets/209838/16305452/eeba8024-3927-11e6-8fca-df92bbe9aac8.png)

**Comment by stuartlynn** [comment]
With some more tests it seams to be working . 4 points 3 on the right 1 on the left with various weightings does what you would expect it to do.


![screen shot 2016-06-23 at 10 49 32 am](https://cloud.githubusercontent.com/assets/209838/16307743/67c59276-3930-11e6-819e-d885f45aa276.png)
![screen shot 2016-06-23 at 10 50 11 am](https://cloud.githubusercontent.com/assets/209838/16307746/6952960c-3930-11e6-91c8-942105241a58.png)
![screen shot 2016-06-23 at 10 50 21 am](https://cloud.githubusercontent.com/assets/209838/16307750/6ad0dd4a-3930-11e6-9f4a-e4969c03a005.png)


I think one of the reasons your not seeing a big effect in the crimes data is the weights are essentially randomly assigned so they will tend to cancel out. If you give crimes where there was an arrest weight 200 and crimes where there wasn't a weight of 1 then the map looks like this:

![screen shot 2016-06-23 at 11 01 05 am](https://cloud.githubusercontent.com/assets/209838/16308168/e6843990-3931-11e6-8be8-8544542f9901.png)

Where the blue points are the unweighted centroids and the orange points are the weighted centroids.

So I think its working ok

**Comment by saleiva** [comment]
retested. Seems like yesterday we fucked up the data or something. You guys win

**Comment by javisantana** [comment]
FAV
