### ISSUE TITLE
don't filter out values for moran's i functions

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/camshaft#97]
@rochoa, on second thought (sorry), it's best not to filter out the rows which have a high significance value. speaking with @makella, we should return all of the values and then have styling to symbolize the values of the quads and significance after that.

**Comment by rochoa** [comment]
We should limit that at builder level: so we don't allow to tweak that parameter from the form. As a user of the builder that makes sense based on what you both are proposing with the styling, but as user of the analysis part I would like to keep that option. What do you think?

**Comment by ohasselblad** [comment]
Having option to do either sounds great. Maybe a checkbox 'only show significant values' would be perfect :) best of both worlds.

**Comment by rochoa** [comment]
Closing issue here, we will track it at https://github.com/CartoDB/cartodb/issues/8686.
