### ISSUE TITLE
enable optimizations for filter only analysis

### ISSUE THREAD

**Issue by javisantana** [CartoDB/camshaft#99]
having this scenario:

```
[points table][A0] -> [buffer][A1] -> [DO measure][A2]
```

adding a histogram widget to A1 and filter makes the A2 to recalcualte again all the rows (which is slow). In this particular case we could just use the same filter than the on applied to [A1] (in other words, it's the same to apply to filter to the A1 output than A2 one)

Obviously this is not always true, not all the analysis work in that but in general augmetation ones could work in that way

(not sure if this ticket belongs here of to windshaft)

cc @saleiva @rochoa

**Comment by saleiva** [comment]
An example is adding data from the DO to a layer, and then filtering that layer.

**Comment by rochoa** [comment]
This belongs here 😈 .

I think we already talked about this: filters are applied at a given node. If that node can provide enough information about its output other nodes consuming from that output can understand that the filter can be applied at next node. Any data augmentation is a clear example for this.
